// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmuVPavwzJkwihUeFzjw6Epxr5yXzhsf4',
    appId: '1:932400963959:web:ba62d98e765d68de4c0172',
    messagingSenderId: '932400963959',
    projectId: 'flutter-123-2300602',
    authDomain: 'flutter-123-2300602.firebaseapp.com',
    storageBucket: 'flutter-123-2300602.firebasestorage.app',
    measurementId: 'G-CXXYH06JCT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAn7WP9z_ArA2vMUIu6Ll1QrOeBW4uecpc',
    appId: '1:932400963959:android:f9159871966537364c0172',
    messagingSenderId: '932400963959',
    projectId: 'flutter-123-2300602',
    storageBucket: 'flutter-123-2300602.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmuVPavwzJkwihUeFzjw6Epxr5yXzhsf4',
    appId: '1:932400963959:web:8cab54ea98a992364c0172',
    messagingSenderId: '932400963959',
    projectId: 'flutter-123-2300602',
    authDomain: 'flutter-123-2300602.firebaseapp.com',
    storageBucket: 'flutter-123-2300602.firebasestorage.app',
    measurementId: 'G-GLZJL1T21K',
  );
}
